import type { Metadata } from "next";
// import { Inter } from 'next/font/google'
import "./globals.css";
import { dmSans, latoRegular } from "@/lib/utils/fonts";
import Providers from "@/lib/utils/providers";
import Navbar from "@/components/Layout/Navbar";

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={dmSans.className}>
        <Providers>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
